# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    groups:
      docusaurus:
        patterns:
          - "@docusaurus*"
          - "docusaurus"
    schedule:
      interval: "weekly"
    assignees:
      - japj
    labels:
      - dependencies
      - npm
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/" # Location of GitHub Actions workflows
    schedule:
      interval: "weekly"
    assignees:
      - japj
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5

  - package-ecosystem: "devcontainers"
    directory: "/" # Location of devcontainer configuration
    schedule:
      interval: "weekly"
    assignees:
      - jap
    labels:
      - dependencies
      - devcontainer
    open-pull-requests-limit: 5
